server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.160.159:3307/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
