server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 59.110.160.159
      database: spitdb
  redis:
    host: 59.110.160.159
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true